Add a retry on reading a file (#84)
To handle errors like:

```
System.IO.IOException: The process cannot access the file 'C:\ProgramData\Octopus\OctopusServer\Instances\e2e-api2primary.config' because it is being used by another process.
```